// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/batsman.dart';
import 'src/models/bowler.dart';
import 'src/models/innings.dart';
import 'src/models/match.dart';
import 'src/models/match_history.dart';
import 'src/models/score.dart';
import 'src/models/team.dart';
import 'src/models/team_member.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5574094097141227077),
    name: 'Team',
    lastPropertyId: const obx_int.IdUid(4, 3702111810584608286),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7480468375241954143),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5497173086096522060),
        name: 'teamId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6160706795430400873),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1009131259175838877),
        name: 'teamName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3702111810584608286),
        name: 'teamCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6275006849892722633),
    name: 'TeamMember',
    lastPropertyId: const obx_int.IdUid(4, 5224547398743552308),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5079742640710249772),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6393149296654824372),
        name: 'playerId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 4646022466543221506),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1614703684759733346),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5224547398743552308),
        name: 'teamName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2775877443378871095),
    name: 'Match',
    lastPropertyId: const obx_int.IdUid(9, 6693471586032238203),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8124953642853590526),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7122228267786482968),
        name: 'matchId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 4379219791951689544),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 435300751899356130),
        name: 'teamId1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6487779178865299046),
        name: 'teamId2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 720098033746807084),
        name: 'tossWonBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1996007448253744580),
        name: 'batBowlFlag',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6812028044889582585),
        name: 'noballFlag',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 54153367472196813),
        name: 'wideFlag',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6693471586032238203),
        name: 'overs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5771647144167435778),
    name: 'Batsman',
    lastPropertyId: const obx_int.IdUid(16, 7165059303953070694),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4088420572437734586),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5640631295779945839),
        name: 'batId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 924819228298571192),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5198926993010661947),
        name: 'inningsId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8818358932573555554),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3876831412952137777),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9147880345533708240),
        name: 'runs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1810379703806973393),
        name: 'ballsFaced',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2813276278636518257),
        name: 'fours',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4161774950214791860),
        name: 'sixes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 314884398396809609),
        name: 'dotBalls',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4366601628030871965),
        name: 'strikeRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6997263092257779014),
        name: 'isOut',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9131031781711442115),
        name: 'bowlerIdWhoGotWicket',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3325063033949880103),
        name: 'dismissalType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2532642610630687409),
        name: 'fielderIdWhoRanOut',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7165059303953070694),
        name: 'extras',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 7473172738024848619),
    name: 'Bowler',
    lastPropertyId: const obx_int.IdUid(12, 299964498781426037),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7874352462220614622),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4026986851683655201),
        name: 'bowlerId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 1739940437194475752),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3104446447273637171),
        name: 'inningsId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7122299040772577920),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5888173803586527440),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8197682045334121819),
        name: 'runsConceded',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1344794256961385713),
        name: 'wickets',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2616293871219319116),
        name: 'balls',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2610485028050056484),
        name: 'overs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7119189378160382921),
        name: 'economy',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7193440485730247566),
        name: 'maidens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 299964498781426037),
        name: 'extras',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7490018871653303460),
    name: 'Innings',
    lastPropertyId: const obx_int.IdUid(8, 2265949672689670304),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2297746571144772817),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4303774017981575384),
        name: 'inningsId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 7791953388720753313),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5351448730515500624),
        name: 'matchId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1168112261925355980),
        name: 'battingTeamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1065986471536019314),
        name: 'bowlingTeamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3955429731988226915),
        name: 'inningsNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1940488668828531455),
        name: 'targetRuns',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2265949672689670304),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8358748761775211892),
    name: 'Score',
    lastPropertyId: const obx_int.IdUid(23, 118584553376461772),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3202345345881361355),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3245361999830721073),
        name: 'inningsId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 3221213037615798870),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2071220658591533711),
        name: 'totalRuns',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7284969305712179306),
        name: 'wickets',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6077449271309245578),
        name: 'overs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 315220103446382026),
        name: 'crr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7076082538681477487),
        name: 'wides',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9082761544624859554),
        name: 'noBalls',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6252751133256139752),
        name: 'byes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3804940553844212385),
        name: 'legByes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8133068684780627964),
        name: 'strikeBatsmanId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6146830876936786659),
        name: 'nonStrikeBatsmanId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1563836339437315989),
        name: 'currentBowlerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 7800591320602354036),
        name: 'currentBall',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 118584553376461772),
        name: 'currentOver',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 5806601655359689055),
    name: 'MatchHistory',
    lastPropertyId: const obx_int.IdUid(14, 635985052740576954),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8624031545939311683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8574342562717312018),
        name: 'matchId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 5652294452443456727),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1981160729957968357),
        name: 'teamAId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8741623518702189329),
        name: 'teamBId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7019266451560385250),
        name: 'matchDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9089093091049421539),
        name: 'matchType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3918764783109079606),
        name: 'team1Runs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5692854300413548885),
        name: 'team1Wickets',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5604759684759806216),
        name: 'team1Overs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3544652407592706100),
        name: 'team2Runs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7613856004563245583),
        name: 'team2Wickets',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 447433220657060415),
        name: 'team2Overs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9035785127381110543),
        name: 'result',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 635985052740576954),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 5806601655359689055),
    lastIndexId: const obx_int.IdUid(8, 5652294452443456727),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2285599034617305271, 3622902142917021616],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6982731572652910135,
      556078640248643897,
      1553385970519105694,
      588452271648312842,
      1555250721491193804,
      6067244635239923110,
      4545569353083856083,
      5107222025575713549,
      9103280526824560048,
      3357192801158175812,
      3096019139704708429,
      5344261324822257753,
      9096136552656286300,
      234305272241868740,
      4121752052603204182,
      4616243808073389807,
      4767596332072826510,
      4323890849868521161,
      2610301113594069623,
      1229282561226367546,
      7397433782792417068,
      1551266224985754926,
      5398473576071983016,
      5644832691181697744,
      2363153043465637192,
      7183824647872641577,
      1698108262597538264,
      7607603083224785413,
      3334566216581240055,
      7138359152693567417,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Team: obx_int.EntityDefinition<Team>(
      model: _entities[0],
      toOneRelations: (Team object) => [],
      toManyRelations: (Team object) => {},
      getId: (Team object) => object.id,
      setId: (Team object, int id) {
        object.id = id;
      },
      objectToFB: (Team object, fb.Builder fbb) {
        final teamIdOffset = fbb.writeString(object.teamId);
        final teamNameOffset = fbb.writeString(object.teamName);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, teamIdOffset);
        fbb.addOffset(2, teamNameOffset);
        fbb.addInt64(3, object.teamCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Team(
          id: idParam,
          teamId: teamIdParam,
          teamName: teamNameParam,
          teamCount: teamCountParam,
        );

        return object;
      },
    ),
    TeamMember: obx_int.EntityDefinition<TeamMember>(
      model: _entities[1],
      toOneRelations: (TeamMember object) => [],
      toManyRelations: (TeamMember object) => {},
      getId: (TeamMember object) => object.id,
      setId: (TeamMember object, int id) {
        object.id = id;
      },
      objectToFB: (TeamMember object, fb.Builder fbb) {
        final playerIdOffset = fbb.writeString(object.playerId);
        final teamIdOffset = fbb.writeString(object.teamId);
        final teamNameOffset = fbb.writeString(object.teamName);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, playerIdOffset);
        fbb.addOffset(2, teamIdOffset);
        fbb.addOffset(3, teamNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = TeamMember(
          id: idParam,
          playerId: playerIdParam,
          teamId: teamIdParam,
          teamName: teamNameParam,
        );

        return object;
      },
    ),
    Match: obx_int.EntityDefinition<Match>(
      model: _entities[2],
      toOneRelations: (Match object) => [],
      toManyRelations: (Match object) => {},
      getId: (Match object) => object.id,
      setId: (Match object, int id) {
        object.id = id;
      },
      objectToFB: (Match object, fb.Builder fbb) {
        final matchIdOffset = fbb.writeString(object.matchId);
        final teamId1Offset = fbb.writeString(object.teamId1);
        final teamId2Offset = fbb.writeString(object.teamId2);
        final tossWonByOffset = fbb.writeString(object.tossWonBy);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, matchIdOffset);
        fbb.addOffset(2, teamId1Offset);
        fbb.addOffset(3, teamId2Offset);
        fbb.addOffset(4, tossWonByOffset);
        fbb.addInt64(5, object.batBowlFlag);
        fbb.addInt64(6, object.noballFlag);
        fbb.addInt64(7, object.wideFlag);
        fbb.addInt64(8, object.overs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final tossWonByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final batBowlFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final noballFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final wideFlagParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final oversParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = Match(
          id: idParam,
          matchId: matchIdParam,
          teamId1: teamId1Param,
          teamId2: teamId2Param,
          tossWonBy: tossWonByParam,
          batBowlFlag: batBowlFlagParam,
          noballFlag: noballFlagParam,
          wideFlag: wideFlagParam,
          overs: oversParam,
        );

        return object;
      },
    ),
    Batsman: obx_int.EntityDefinition<Batsman>(
      model: _entities[3],
      toOneRelations: (Batsman object) => [],
      toManyRelations: (Batsman object) => {},
      getId: (Batsman object) => object.id,
      setId: (Batsman object, int id) {
        object.id = id;
      },
      objectToFB: (Batsman object, fb.Builder fbb) {
        final batIdOffset = fbb.writeString(object.batId);
        final inningsIdOffset = fbb.writeString(object.inningsId);
        final teamIdOffset = fbb.writeString(object.teamId);
        final playerIdOffset = fbb.writeString(object.playerId);
        final bowlerIdWhoGotWicketOffset = object.bowlerIdWhoGotWicket == null
            ? null
            : fbb.writeString(object.bowlerIdWhoGotWicket!);
        final dismissalTypeOffset = object.dismissalType == null
            ? null
            : fbb.writeString(object.dismissalType!);
        final fielderIdWhoRanOutOffset = object.fielderIdWhoRanOut == null
            ? null
            : fbb.writeString(object.fielderIdWhoRanOut!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, batIdOffset);
        fbb.addOffset(2, inningsIdOffset);
        fbb.addOffset(3, teamIdOffset);
        fbb.addOffset(4, playerIdOffset);
        fbb.addInt64(5, object.runs);
        fbb.addInt64(6, object.ballsFaced);
        fbb.addInt64(7, object.fours);
        fbb.addInt64(8, object.sixes);
        fbb.addInt64(9, object.dotBalls);
        fbb.addFloat64(10, object.strikeRate);
        fbb.addBool(11, object.isOut);
        fbb.addOffset(12, bowlerIdWhoGotWicketOffset);
        fbb.addOffset(13, dismissalTypeOffset);
        fbb.addOffset(14, fielderIdWhoRanOutOffset);
        fbb.addInt64(15, object.extras);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final batIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final inningsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final runsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final ballsFacedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final foursParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final sixesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final dotBallsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final extrasParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final strikeRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final isOutParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final bowlerIdWhoGotWicketParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final dismissalTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final fielderIdWhoRanOutParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final object = Batsman(
          id: idParam,
          batId: batIdParam,
          inningsId: inningsIdParam,
          teamId: teamIdParam,
          playerId: playerIdParam,
          runs: runsParam,
          ballsFaced: ballsFacedParam,
          fours: foursParam,
          sixes: sixesParam,
          dotBalls: dotBallsParam,
          extras: extrasParam,
          strikeRate: strikeRateParam,
          isOut: isOutParam,
          bowlerIdWhoGotWicket: bowlerIdWhoGotWicketParam,
          dismissalType: dismissalTypeParam,
          fielderIdWhoRanOut: fielderIdWhoRanOutParam,
        );

        return object;
      },
    ),
    Bowler: obx_int.EntityDefinition<Bowler>(
      model: _entities[4],
      toOneRelations: (Bowler object) => [],
      toManyRelations: (Bowler object) => {},
      getId: (Bowler object) => object.id,
      setId: (Bowler object, int id) {
        object.id = id;
      },
      objectToFB: (Bowler object, fb.Builder fbb) {
        final bowlerIdOffset = fbb.writeString(object.bowlerId);
        final inningsIdOffset = fbb.writeString(object.inningsId);
        final teamIdOffset = fbb.writeString(object.teamId);
        final playerIdOffset = fbb.writeString(object.playerId);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, bowlerIdOffset);
        fbb.addOffset(2, inningsIdOffset);
        fbb.addOffset(3, teamIdOffset);
        fbb.addOffset(4, playerIdOffset);
        fbb.addInt64(5, object.runsConceded);
        fbb.addInt64(6, object.wickets);
        fbb.addInt64(7, object.balls);
        fbb.addFloat64(8, object.overs);
        fbb.addFloat64(9, object.economy);
        fbb.addInt64(10, object.maidens);
        fbb.addInt64(11, object.extras);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final bowlerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final inningsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final runsConcededParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final wicketsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final ballsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final maidensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final extrasParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final oversParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final economyParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = Bowler(
          id: idParam,
          bowlerId: bowlerIdParam,
          inningsId: inningsIdParam,
          teamId: teamIdParam,
          playerId: playerIdParam,
          runsConceded: runsConcededParam,
          wickets: wicketsParam,
          balls: ballsParam,
          maidens: maidensParam,
          extras: extrasParam,
          overs: oversParam,
          economy: economyParam,
        );

        return object;
      },
    ),
    Innings: obx_int.EntityDefinition<Innings>(
      model: _entities[5],
      toOneRelations: (Innings object) => [],
      toManyRelations: (Innings object) => {},
      getId: (Innings object) => object.id,
      setId: (Innings object, int id) {
        object.id = id;
      },
      objectToFB: (Innings object, fb.Builder fbb) {
        final inningsIdOffset = fbb.writeString(object.inningsId);
        final matchIdOffset = fbb.writeString(object.matchId);
        final battingTeamIdOffset = fbb.writeString(object.battingTeamId);
        final bowlingTeamIdOffset = fbb.writeString(object.bowlingTeamId);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, inningsIdOffset);
        fbb.addOffset(2, matchIdOffset);
        fbb.addOffset(3, battingTeamIdOffset);
        fbb.addOffset(4, bowlingTeamIdOffset);
        fbb.addInt64(5, object.inningsNumber);
        fbb.addInt64(6, object.targetRuns);
        fbb.addBool(7, object.isCompleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final inningsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final battingTeamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final bowlingTeamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final inningsNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final targetRunsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = Innings(
          id: idParam,
          inningsId: inningsIdParam,
          matchId: matchIdParam,
          battingTeamId: battingTeamIdParam,
          bowlingTeamId: bowlingTeamIdParam,
          inningsNumber: inningsNumberParam,
          targetRuns: targetRunsParam,
          isCompleted: isCompletedParam,
        );

        return object;
      },
    ),
    Score: obx_int.EntityDefinition<Score>(
      model: _entities[6],
      toOneRelations: (Score object) => [],
      toManyRelations: (Score object) => {},
      getId: (Score object) => object.id,
      setId: (Score object, int id) {
        object.id = id;
      },
      objectToFB: (Score object, fb.Builder fbb) {
        final inningsIdOffset = fbb.writeString(object.inningsId);
        final strikeBatsmanIdOffset = fbb.writeString(object.strikeBatsmanId);
        final nonStrikeBatsmanIdOffset = fbb.writeString(
          object.nonStrikeBatsmanId,
        );
        final currentBowlerIdOffset = fbb.writeString(object.currentBowlerId);
        final currentOverOffset = fbb.writeList(
          object.currentOver.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, inningsIdOffset);
        fbb.addInt64(2, object.totalRuns);
        fbb.addInt64(3, object.wickets);
        fbb.addFloat64(5, object.overs);
        fbb.addFloat64(6, object.crr);
        fbb.addInt64(14, object.wides);
        fbb.addInt64(15, object.noBalls);
        fbb.addInt64(16, object.byes);
        fbb.addInt64(17, object.legByes);
        fbb.addOffset(18, strikeBatsmanIdOffset);
        fbb.addOffset(19, nonStrikeBatsmanIdOffset);
        fbb.addOffset(20, currentBowlerIdOffset);
        fbb.addInt64(21, object.currentBall);
        fbb.addOffset(22, currentOverOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final inningsIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final totalRunsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final wicketsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final oversParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final crrParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final widesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final noBallsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final byesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final legByesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final strikeBatsmanIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final nonStrikeBatsmanIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final currentBowlerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final currentBallParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final object =
            Score(
                id: idParam,
                inningsId: inningsIdParam,
                totalRuns: totalRunsParam,
                wickets: wicketsParam,
                overs: oversParam,
                crr: crrParam,
                wides: widesParam,
                noBalls: noBallsParam,
                byes: byesParam,
                legByes: legByesParam,
                strikeBatsmanId: strikeBatsmanIdParam,
                nonStrikeBatsmanId: nonStrikeBatsmanIdParam,
                currentBowlerId: currentBowlerIdParam,
                currentBall: currentBallParam,
              )
              ..currentOver = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 48, []);

        return object;
      },
    ),
    MatchHistory: obx_int.EntityDefinition<MatchHistory>(
      model: _entities[7],
      toOneRelations: (MatchHistory object) => [],
      toManyRelations: (MatchHistory object) => {},
      getId: (MatchHistory object) => object.id,
      setId: (MatchHistory object, int id) {
        object.id = id;
      },
      objectToFB: (MatchHistory object, fb.Builder fbb) {
        final matchIdOffset = fbb.writeString(object.matchId);
        final teamAIdOffset = fbb.writeString(object.teamAId);
        final teamBIdOffset = fbb.writeString(object.teamBId);
        final matchTypeOffset = fbb.writeString(object.matchType);
        final resultOffset = fbb.writeString(object.result);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, matchIdOffset);
        fbb.addOffset(2, teamAIdOffset);
        fbb.addOffset(3, teamBIdOffset);
        fbb.addInt64(4, object.matchDate.millisecondsSinceEpoch);
        fbb.addOffset(5, matchTypeOffset);
        fbb.addInt64(6, object.team1Runs);
        fbb.addInt64(7, object.team1Wickets);
        fbb.addFloat64(8, object.team1Overs);
        fbb.addInt64(9, object.team2Runs);
        fbb.addInt64(10, object.team2Wickets);
        fbb.addFloat64(11, object.team2Overs);
        fbb.addOffset(12, resultOffset);
        fbb.addBool(13, object.isCompleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final teamAIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamBIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final matchDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final matchTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final team1RunsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final team1WicketsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final team1OversParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final team2RunsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final team2WicketsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final team2OversParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final resultParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final object = MatchHistory(
          id: idParam,
          matchId: matchIdParam,
          teamAId: teamAIdParam,
          teamBId: teamBIdParam,
          matchDate: matchDateParam,
          matchType: matchTypeParam,
          team1Runs: team1RunsParam,
          team1Wickets: team1WicketsParam,
          team1Overs: team1OversParam,
          team2Runs: team2RunsParam,
          team2Wickets: team2WicketsParam,
          team2Overs: team2OversParam,
          result: resultParam,
          isCompleted: isCompletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Team] entity fields to define ObjectBox queries.
class Team_ {
  /// See [Team.id].
  static final id = obx.QueryIntegerProperty<Team>(_entities[0].properties[0]);

  /// See [Team.teamId].
  static final teamId = obx.QueryStringProperty<Team>(
    _entities[0].properties[1],
  );

  /// See [Team.teamName].
  static final teamName = obx.QueryStringProperty<Team>(
    _entities[0].properties[2],
  );

  /// See [Team.teamCount].
  static final teamCount = obx.QueryIntegerProperty<Team>(
    _entities[0].properties[3],
  );
}

/// [TeamMember] entity fields to define ObjectBox queries.
class TeamMember_ {
  /// See [TeamMember.id].
  static final id = obx.QueryIntegerProperty<TeamMember>(
    _entities[1].properties[0],
  );

  /// See [TeamMember.playerId].
  static final playerId = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[1],
  );

  /// See [TeamMember.teamId].
  static final teamId = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[2],
  );

  /// See [TeamMember.teamName].
  static final teamName = obx.QueryStringProperty<TeamMember>(
    _entities[1].properties[3],
  );
}

/// [Match] entity fields to define ObjectBox queries.
class Match_ {
  /// See [Match.id].
  static final id = obx.QueryIntegerProperty<Match>(_entities[2].properties[0]);

  /// See [Match.matchId].
  static final matchId = obx.QueryStringProperty<Match>(
    _entities[2].properties[1],
  );

  /// See [Match.teamId1].
  static final teamId1 = obx.QueryStringProperty<Match>(
    _entities[2].properties[2],
  );

  /// See [Match.teamId2].
  static final teamId2 = obx.QueryStringProperty<Match>(
    _entities[2].properties[3],
  );

  /// See [Match.tossWonBy].
  static final tossWonBy = obx.QueryStringProperty<Match>(
    _entities[2].properties[4],
  );

  /// See [Match.batBowlFlag].
  static final batBowlFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[5],
  );

  /// See [Match.noballFlag].
  static final noballFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[6],
  );

  /// See [Match.wideFlag].
  static final wideFlag = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[7],
  );

  /// See [Match.overs].
  static final overs = obx.QueryIntegerProperty<Match>(
    _entities[2].properties[8],
  );
}

/// [Batsman] entity fields to define ObjectBox queries.
class Batsman_ {
  /// See [Batsman.id].
  static final id = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[0],
  );

  /// See [Batsman.batId].
  static final batId = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[1],
  );

  /// See [Batsman.inningsId].
  static final inningsId = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[2],
  );

  /// See [Batsman.teamId].
  static final teamId = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[3],
  );

  /// See [Batsman.playerId].
  static final playerId = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[4],
  );

  /// See [Batsman.runs].
  static final runs = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[5],
  );

  /// See [Batsman.ballsFaced].
  static final ballsFaced = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[6],
  );

  /// See [Batsman.fours].
  static final fours = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[7],
  );

  /// See [Batsman.sixes].
  static final sixes = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[8],
  );

  /// See [Batsman.dotBalls].
  static final dotBalls = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[9],
  );

  /// See [Batsman.strikeRate].
  static final strikeRate = obx.QueryDoubleProperty<Batsman>(
    _entities[3].properties[10],
  );

  /// See [Batsman.isOut].
  static final isOut = obx.QueryBooleanProperty<Batsman>(
    _entities[3].properties[11],
  );

  /// See [Batsman.bowlerIdWhoGotWicket].
  static final bowlerIdWhoGotWicket = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[12],
  );

  /// See [Batsman.dismissalType].
  static final dismissalType = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[13],
  );

  /// See [Batsman.fielderIdWhoRanOut].
  static final fielderIdWhoRanOut = obx.QueryStringProperty<Batsman>(
    _entities[3].properties[14],
  );

  /// See [Batsman.extras].
  static final extras = obx.QueryIntegerProperty<Batsman>(
    _entities[3].properties[15],
  );
}

/// [Bowler] entity fields to define ObjectBox queries.
class Bowler_ {
  /// See [Bowler.id].
  static final id = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[0],
  );

  /// See [Bowler.bowlerId].
  static final bowlerId = obx.QueryStringProperty<Bowler>(
    _entities[4].properties[1],
  );

  /// See [Bowler.inningsId].
  static final inningsId = obx.QueryStringProperty<Bowler>(
    _entities[4].properties[2],
  );

  /// See [Bowler.teamId].
  static final teamId = obx.QueryStringProperty<Bowler>(
    _entities[4].properties[3],
  );

  /// See [Bowler.playerId].
  static final playerId = obx.QueryStringProperty<Bowler>(
    _entities[4].properties[4],
  );

  /// See [Bowler.runsConceded].
  static final runsConceded = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[5],
  );

  /// See [Bowler.wickets].
  static final wickets = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[6],
  );

  /// See [Bowler.balls].
  static final balls = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[7],
  );

  /// See [Bowler.overs].
  static final overs = obx.QueryDoubleProperty<Bowler>(
    _entities[4].properties[8],
  );

  /// See [Bowler.economy].
  static final economy = obx.QueryDoubleProperty<Bowler>(
    _entities[4].properties[9],
  );

  /// See [Bowler.maidens].
  static final maidens = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[10],
  );

  /// See [Bowler.extras].
  static final extras = obx.QueryIntegerProperty<Bowler>(
    _entities[4].properties[11],
  );
}

/// [Innings] entity fields to define ObjectBox queries.
class Innings_ {
  /// See [Innings.id].
  static final id = obx.QueryIntegerProperty<Innings>(
    _entities[5].properties[0],
  );

  /// See [Innings.inningsId].
  static final inningsId = obx.QueryStringProperty<Innings>(
    _entities[5].properties[1],
  );

  /// See [Innings.matchId].
  static final matchId = obx.QueryStringProperty<Innings>(
    _entities[5].properties[2],
  );

  /// See [Innings.battingTeamId].
  static final battingTeamId = obx.QueryStringProperty<Innings>(
    _entities[5].properties[3],
  );

  /// See [Innings.bowlingTeamId].
  static final bowlingTeamId = obx.QueryStringProperty<Innings>(
    _entities[5].properties[4],
  );

  /// See [Innings.inningsNumber].
  static final inningsNumber = obx.QueryIntegerProperty<Innings>(
    _entities[5].properties[5],
  );

  /// See [Innings.targetRuns].
  static final targetRuns = obx.QueryIntegerProperty<Innings>(
    _entities[5].properties[6],
  );

  /// See [Innings.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Innings>(
    _entities[5].properties[7],
  );
}

/// [Score] entity fields to define ObjectBox queries.
class Score_ {
  /// See [Score.id].
  static final id = obx.QueryIntegerProperty<Score>(_entities[6].properties[0]);

  /// See [Score.inningsId].
  static final inningsId = obx.QueryStringProperty<Score>(
    _entities[6].properties[1],
  );

  /// See [Score.totalRuns].
  static final totalRuns = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[2],
  );

  /// See [Score.wickets].
  static final wickets = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[3],
  );

  /// See [Score.overs].
  static final overs = obx.QueryDoubleProperty<Score>(
    _entities[6].properties[4],
  );

  /// See [Score.crr].
  static final crr = obx.QueryDoubleProperty<Score>(_entities[6].properties[5]);

  /// See [Score.wides].
  static final wides = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[6],
  );

  /// See [Score.noBalls].
  static final noBalls = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[7],
  );

  /// See [Score.byes].
  static final byes = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[8],
  );

  /// See [Score.legByes].
  static final legByes = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[9],
  );

  /// See [Score.strikeBatsmanId].
  static final strikeBatsmanId = obx.QueryStringProperty<Score>(
    _entities[6].properties[10],
  );

  /// See [Score.nonStrikeBatsmanId].
  static final nonStrikeBatsmanId = obx.QueryStringProperty<Score>(
    _entities[6].properties[11],
  );

  /// See [Score.currentBowlerId].
  static final currentBowlerId = obx.QueryStringProperty<Score>(
    _entities[6].properties[12],
  );

  /// See [Score.currentBall].
  static final currentBall = obx.QueryIntegerProperty<Score>(
    _entities[6].properties[13],
  );

  /// See [Score.currentOver].
  static final currentOver = obx.QueryStringVectorProperty<Score>(
    _entities[6].properties[14],
  );
}

/// [MatchHistory] entity fields to define ObjectBox queries.
class MatchHistory_ {
  /// See [MatchHistory.id].
  static final id = obx.QueryIntegerProperty<MatchHistory>(
    _entities[7].properties[0],
  );

  /// See [MatchHistory.matchId].
  static final matchId = obx.QueryStringProperty<MatchHistory>(
    _entities[7].properties[1],
  );

  /// See [MatchHistory.teamAId].
  static final teamAId = obx.QueryStringProperty<MatchHistory>(
    _entities[7].properties[2],
  );

  /// See [MatchHistory.teamBId].
  static final teamBId = obx.QueryStringProperty<MatchHistory>(
    _entities[7].properties[3],
  );

  /// See [MatchHistory.matchDate].
  static final matchDate = obx.QueryDateProperty<MatchHistory>(
    _entities[7].properties[4],
  );

  /// See [MatchHistory.matchType].
  static final matchType = obx.QueryStringProperty<MatchHistory>(
    _entities[7].properties[5],
  );

  /// See [MatchHistory.team1Runs].
  static final team1Runs = obx.QueryIntegerProperty<MatchHistory>(
    _entities[7].properties[6],
  );

  /// See [MatchHistory.team1Wickets].
  static final team1Wickets = obx.QueryIntegerProperty<MatchHistory>(
    _entities[7].properties[7],
  );

  /// See [MatchHistory.team1Overs].
  static final team1Overs = obx.QueryDoubleProperty<MatchHistory>(
    _entities[7].properties[8],
  );

  /// See [MatchHistory.team2Runs].
  static final team2Runs = obx.QueryIntegerProperty<MatchHistory>(
    _entities[7].properties[9],
  );

  /// See [MatchHistory.team2Wickets].
  static final team2Wickets = obx.QueryIntegerProperty<MatchHistory>(
    _entities[7].properties[10],
  );

  /// See [MatchHistory.team2Overs].
  static final team2Overs = obx.QueryDoubleProperty<MatchHistory>(
    _entities[7].properties[11],
  );

  /// See [MatchHistory.result].
  static final result = obx.QueryStringProperty<MatchHistory>(
    _entities[7].properties[12],
  );

  /// See [MatchHistory.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<MatchHistory>(
    _entities[7].properties[13],
  );
}
